name=input("Enter your name.")
age=int(input("nter your age"))
is-boolean=bool("Are you a student?,True or False")
weight=float()
print("Name:",name)
print("type of name:", type(name))
print("age:",age)
print("type of age:", type(age))
print("is student:",is-boolean)
print("type of name:", type(is-boolean))
print("weight:",weight)
print("type of weight:", type(weight))
print("\n After type casting .......")
age=str(age)
print(age)
print("type of age:", type(age))
weight=int(weight)
print(weight)
print("type of weight:", type(weight))